encoding:       'utf-8'
markdown:       kramdown
highlighter:    pygments
paginate:       10
paginate_path:  "news/page:num"

title:          ACM HONORED CLASS
baseurl:        "http://fei960922.github.io/ACM_Website_2014"
url:            "http://fei960922.github.io/ACM_Website_2014"
permalink:      /:categories/:title/

footer:
      
copyright:
    - Design by ACM HONORED CLASS
    - "&copy; Copyright 2014, ACM HONORED CLASS. All Rights Reserved."
      
css:
    - /lib/style.css
    - /lib/syntax.css
    - /lib/buttons.css
    
